spring.application.name=SpringBootSample_2


#DataSource
#spring boot起動時にテーブル作成と初期データの投入のSQLを実行するために設定

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.data-username=sa
spring.datasource.data-password=
spring.datasource.sql-script-encoding=UTF-8

spring.datasource.schema=classpath:schema.sql
#テーブル作成のSQLを実行

#H2DB
spring.h2.console.enabled=true

#MyBatis
#xmlファイルの置き場所を指定
mybatis.mapper-locations=classpath*:/mapper/h2/*.xml

#MUserなどのデーター型を設定する場合、パッケージ名も含める必要がある
mybatis.type-aliases-package=com.example.domain.user.model

spring.messages.basename=i18n/ValidationMessages

